SECRET_KEY = '76AFC0778E648BDA05705047BAFA96ED'

TEST_POST = {
	u'caccountamount': u'3322',
	u'cnoticeversion': u'4.0',
	u'cbf': u'6NL5FMRERQ',
	u'ctranspaymentmethod': u'TEST',
	u'corderamount': u'3700',
	u'ctaxamount': u'0',
	u'ccustzip': u'12491',
	u'ctransreceipt': u'J5ZD69EL',
	u'ccustfullname': u'Ethan Claus',
	u'ctid': u'',
	u'corderlanguage': u'EN',
	u'ccustcounty': u'Something',
	u'ccustcc': u'US',
	u'ccuststate': u'TX',
	u'cbfpath': u'',
	u'cfuturepayments': u'',
	u'crebillamnt': u'',
	u'ccustaddr2': u'',
	u'cshippingamount': u'0',
	u'ctransaction': u'TEST_SALE',
	u'ctransvendor': u'aproductid',
	u'cverify': u'83F3F41B',
	u'ccustshippingzip': u'78758',
	u'ctransaffiliate': u'',
	u'ccustemail': u'email@aol.com',
	u'cupsellreceipt': u'',
	u'cprodtitle': u'Product Title',
	u'ctransrole': u'VENDOR',
	u'crebillstatus': u'',
	u'cbfid': u'12425',
	u'cvendthru': u'cbfid=12425&email=email%40aol.com&customer_id=999&cbskin=5505&',
	u'cprodtype': u'STANDARD',
	u'ccustfirstname': u'Ethan',
	u'ctranstime': u'1383932433',
	u'ccurrency': u'USD',
	u'cprocessedpayments': u'',
	u'ccustshippingcountry': u'US',
	u'ccustlastname': u'Claus',
	u'cnextpaymentdate': u'',
	u'cproditem': u'1037',
	u'ccustaddr1': u'',
	u'ccustcity': u'',
	u'crebillfrequency': u'',
	u'ccustshippingstate': u'TX'
}
TEST_POST_2 = {
	u'caccountamount': u'100',
	u'cnoticeversion': u'4.0',
	u'cbf': u'',
	u'ctranspaymentmethod': u'VISA',
	u'corderamount': u'100',
	u'ctaxamount': u'0',
	u'ccustzip': u'',
	u'ctransreceipt': u'********',
	u'ccustfullname': u'Test User',
	u'ctid': u'',
	u'corderlanguage': u'',
	u'ccustcounty': u'',
	u'ccustcc': u'',
	u'ccuststate': u'',
	u'cbfpath': u'',
	u'cfuturepayments': u'',
	u'crebillamnt': u'',
	u'ccustaddr2': u'',
	u'cshippingamount': u'0',
	u'ctransaction': u'TEST',
	u'ctransvendor': u'csmsurvive',
	u'cverify': u'007806EC',
	u'ccustshippingzip': u'',
	u'ctransaffiliate': u'',
	u'ccustemail': u'testuser@somesite.com',
	u'cupsellreceipt': u'',
	u'cprodtitle': u'A passed in title',
	u'ctransrole': u'VENDOR',
	u'crebillstatus': u'',
	u'cbfid': u'',
	u'cvendthru': u'',
	u'cprodtype': u'STANDARD',
	u'ccustfirstname': u'TEST',
	u'ctranstime': u'1383333571',
	u'ccurrency': u'USD',
	u'cprocessedpayments': u'',
	u'ccustshippingcountry': u'',
	u'ccustlastname': u'USER',
	u'cnextpaymentdate': u'',
	u'cproditem': u'1',
	u'ccustaddr1': u'',
	u'ccustcity': u'',
	u'crebillfrequency': u'',
	u'ccustshippingstate': u''
}

TEST_POST_3 = {
	"caccountamount": "830",
	"cnoticeversion": "4.0",
	"cbf": "TXPREK4FTY",
	"ctranspaymentmethod": "VISA",
	"corderamount": "3700",
	"ctaxamount": "0",
	"ccustzip": "83527",
	"ctransreceipt": "7965F6NE",
	"ccustfullname": " Toshe M Atlas ",
	"ctid": "FULLPRICE",
	"corderlanguage": "EN",
	"ccustcounty": "MORGAN",
	"ccustcc": "US",
	"ccuststate": "MO",
	"cbfpath": "",
	"cfuturepayments": "",
	"crebillamnt": "",
	"ccustaddr2": "",
	"cshippingamount": "0",
	"ctransaction": "SALE",
	"ctransvendor": "csmsurvive",
	"cverify": "73707949",
	"ccustshippingzip": "65038",
	"ctransaffiliate": "survive77",
	"ccustemail": "oneotherusername@yahoo.com",
	"cupsellreceipt": "",
	"cprodtitle": "Product Titles^",
	"ctransrole": "VENDOR",
	"crebillstatus": "",
	"cbfid": "12345",
	"cvendthru": "cbskin=5505&cbfid=12425&vtid=fullprice&email=nndysyshs%40yahoo.com&customer_id=976&",
	"cprodtype": "STANDARD",
	"ccustfirstname": "Toshe",
	"ctranstime": "1383864458",
	"ccurrency": "USD",
	"cprocessedpayments": "",
	"ccustshippingcountry": "US",
	"ccustlastname": "Atlas",
	"cnextpaymentdate": "",
	"cproditem": "1037",
	"ccustaddr1": "",
	"ccustcity": "LAURIE",
	"crebillfrequency": "",
	"ccustshippingstate": "MO"
}

TEST_POST_4 = {
	'caccountamount': ['873'],
	'cbf': ['ZBN24EFBTG'],
	'cbfid': ['12425'],
	'cbfpath': ['aa'],
	'ccurrency': ['USD'],
	'ccustcc': ['US'],
	'ccustcounty': ['KING'],
	'ccustemail': ['jkdfjuklsd@comcast.net'],
	'ccustfirstname': ['Sylvia'],
	'ccustfullname': ['Sylvia Jones'],
	'ccustlastname': ['Jones'],
	'ccustshippingcountry': ['US'],
	'ccustshippingstate': ['WA'],
	'ccustshippingzip': ['98118'],
	'ccuststate': ['WA'],
	'ccustzip': ['98118'],
	'cfuturepayments': ['998'],
	'cnextpaymentdate': ['2013-12-12'],
	'cnoticeversion': ['4.0'],
	'corderamount': ['1995'],
	'corderlanguage': ['EN'],
	'cprocessedpayments': ['1'],
	'cproditem': ['2019'],
	'cprodtitle': ['United Survivalists Association'],
	'cprodtype': ['RECURRING'],
	'crebillamnt': ['1995'],
	'crebillfrequency': ['MONTHLY'],
	'crebillstatus': ['ACTIVE'],
	'cshippingamount': ['0'],
	'ctaxamount': ['0'],
	'ctransaction': ['SALE'],
	'ctransaffiliate': ['firbles'],
	'ctranspaymentmethod': ['AMEX'],
	'ctransreceipt': ['V73D6CED'],
	'ctransrole': ['VENDOR'],
	'ctranstime': ['1384273975'],
	'ctransvendor': ['csmsurvive'],
	'cupsellreceipt': ['DFZREKMH'],
	'cvendthru': ['cupsellreceipt=DFZREKMH&cbf=ZBN24EFBTG&cbrblaccpt=true&y=52&customer_id=1118&x=196&cbur=a&'],
	'cverify': ['C41E25C1']
}


TEST_POSTS = [TEST_POST, TEST_POST_2, TEST_POST_3, TEST_POST_4]