language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install -r test-requirements.txt --use-mirrors"
  - "pip install coveralls --use-mirrors"
# command to run tests
script:
  - "pip install -r test-requirements.txt"
  - "coverage run --source=django_clickbank runtests.py"
after_success:
  coveralls