SECRET_KEY = '76AFC0778E648BDA05705047BAFA96ED'

TEST_POST = {
	u'caccountamount': u'100',
	u'ctranspaymentmethod': u'VISA',
	u'corderamount': u'100',
	u'ccustzip': u'',
	u'ctransreceipt': u'********',
	u'cupsellreceipt': u'',
	u'ccustfullname': u'Test User',
	u'ctid': u'',
	u'ccustcounty': u'',
	u'ccustcc': u'',
	u'ccuststate': u'',
	u'cfuturepayments': u'',
	u'crebillamnt': u'',
	u'ccustaddr2': u'',
	u'ccustaddr1': u'',
	u'ctransaction': u'TEST',
	u'cverify': u'30975154',
	u'ccustshippingzip': u'',
	u'ctransaffiliate': u'',
	u'ccustemail': u'testuser@somesite.com',
	u'cprocessedpayments': u'',
	u'cprodtitle': u'A passed in title',
	u'ctransrole': u'VENDOR',
	u'ctranspublisher': u'csmsurvive',
	u'crebillstatus': u'',
	u'cvendthru': u'',
	u'cprodtype': u'STANDARD',
	u'ccustfirstname': u'TEST',
	u'ctranstime': u'1383333296',
	u'ccurrency': u'USD',
	u'ccustcity': u'',
	u'ccustshippingcountry': u'',
	u'ccustlastname': u'USER',
	u'cnextpaymentdate': u'',
	u'cproditem': u'1',
	u'ccustshippingstate': u''
}

TEST_POST_2 = {
	u'caccountamount': u'100',
	u'cnoticeversion': u'4.0',
	u'cbf': u'',
	u'ctranspaymentmethod': u'VISA',
	u'corderamount': u'100',
	u'ctaxamount': u'0',
	u'ccustzip': u'',
	u'ctransreceipt': u'********',
	u'ccustfullname': u'Test User',
	u'ctid': u'',
	u'corderlanguage': u'',
	u'ccustcounty': u'',
	u'ccustcc': u'',
	u'ccuststate': u'',
	u'cbfpath': u'',
	u'cfuturepayments': u'',
	u'crebillamnt': u'',
	u'ccustaddr2': u'',
	u'cshippingamount': u'0',
	u'ctransaction': u'TEST',
	u'ctransvendor': u'csmsurvive',
	u'cverify': u'007806EC',
	u'ccustshippingzip': u'',
	u'ctransaffiliate': u'',
	u'ccustemail': u'testuser@somesite.com',
	u'cupsellreceipt': u'',
	u'cprodtitle': u'A passed in title',
	u'ctransrole': u'VENDOR',
	u'crebillstatus': u'',
	u'cbfid': u'',
	u'cvendthru': u'',
	u'cprodtype': u'STANDARD',
	u'ccustfirstname': u'TEST',
	u'ctranstime': u'1383333571',
	u'ccurrency': u'USD',
	u'cprocessedpayments': u'',
	u'ccustshippingcountry': u'',
	u'ccustlastname': u'USER',
	u'cnextpaymentdate': u'',
	u'cproditem': u'1',
	u'ccustaddr1': u'',
	u'ccustcity': u'',
	u'crebillfrequency': u'',
	u'ccustshippingstate': u''
}
TEST_POSTS = [TEST_POST, TEST_POST_2,]